server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    include-stacktrace: always
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/syncProductDb
    username: syncProductDbUser
    password: syncProductDbPassword
    hikari:
      maximum-pool-size: 3
  flyway:
    baseline-on-migrate: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false